//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaNegocio.Lenguajes {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errores() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogicaNegocio.Lenguajes.Errores", typeof(Errores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso.
        /// </summary>
        public static string Aviso {
            get {
                return ResourceManager.GetString("Aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo debe contener 11 digitos..
        /// </summary>
        public static string CampoMinimo11 {
            get {
                return ResourceManager.GetString("CampoMinimo11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay campos incompletos..
        /// </summary>
        public static string CamposIncompletos {
            get {
                return ResourceManager.GetString("CamposIncompletos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este empleado ya tiene un pedido de certificación de servicios en los últimos 30 días..
        /// </summary>
        public static string Cer30Dias {
            get {
                return ResourceManager.GetString("Cer30Dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El codigo ingresado ha expirado..
        /// </summary>
        public static string CodigoExpirado {
            get {
                return ResourceManager.GetString("CodigoExpirado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El codigo ingresado es incorrecto..
        /// </summary>
        public static string CodigoIncorrecto {
            get {
                return ResourceManager.GetString("CodigoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico no es válido..
        /// </summary>
        public static string CorreoNoValido {
            get {
                return ResourceManager.GetString("CorreoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cuil ingresado no tiene un formato correcto..
        /// </summary>
        public static string CuilIncorrecto {
            get {
                return ResourceManager.GetString("CuilIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Cuit/Cuil ya esta asociado a un empleado..
        /// </summary>
        public static string CuitEnUso {
            get {
                return ResourceManager.GetString("CuitEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descarga fue realizada con éxito..
        /// </summary>
        public static string DescargaExitosa {
            get {
                return ResourceManager.GetString("DescargaExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descarga fue realizada con éxito..
        /// </summary>
        public static string DescargarExitosa {
            get {
                return ResourceManager.GetString("DescargarExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro se encuentra en uso..
        /// </summary>
        public static string DocEnUso {
            get {
                return ResourceManager.GetString("DocEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La entrevista ya está ingresada. Por favor, ingrese otra..
        /// </summary>
        public static string EntYaIngresada {
            get {
                return ResourceManager.GetString("EntYaIngresada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha habido un error al intentar dar de alta..
        /// </summary>
        public static string ErrorAlta {
            get {
                return ResourceManager.GetString("ErrorAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar enviar el email.
        /// </summary>
        public static string ErrorMail {
            get {
                return ResourceManager.GetString("ErrorMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las etapas no coinciden. No se puede completar el DataGridView..
        /// </summary>
        public static string EtapasNoCoinciden {
            get {
                return ResourceManager.GetString("EtapasNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor de etapa no es un número válido..
        /// </summary>
        public static string EtapNoValida {
            get {
                return ResourceManager.GetString("EtapNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utilice al menos un filtro..
        /// </summary>
        public static string FiltroIncompleto {
            get {
                return ResourceManager.GetString("FiltroIncompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede repetir el idioma..
        /// </summary>
        public static string IdiomaRepetido {
            get {
                return ResourceManager.GetString("IdiomaRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información académica es obligatoria..
        /// </summary>
        public static string InfoAcademicaOb {
            get {
                return ResourceManager.GetString("InfoAcademicaOb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limite de intentos alcanzado, intente nuevamente a las.
        /// </summary>
        public static string LiminteIntentos {
            get {
                return ResourceManager.GetString("LiminteIntentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MODIFICACION NO AUTORIZADA DE LA BASE DE DATOS..
        /// </summary>
        public static string ModNoAutorizada {
            get {
                return ResourceManager.GetString("ModNoAutorizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación Exitosa..
        /// </summary>
        public static string OperacionExitosa {
            get {
                return ResourceManager.GetString("OperacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No incluir datos personales..
        /// </summary>
        public static string PasDatos {
            get {
                return ResourceManager.GetString("PasDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no cumple con una o más de los requisitos..
        /// </summary>
        public static string PasFaltaCriterio {
            get {
                return ResourceManager.GetString("PasFaltaCriterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimo ocho caracteres..
        /// </summary>
        public static string PasMinimo8 {
            get {
                return ResourceManager.GetString("PasMinimo8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimo un caracter especial..
        /// </summary>
        public static string PasMinimoEsp {
            get {
                return ResourceManager.GetString("PasMinimoEsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimo una mayuscula..
        /// </summary>
        public static string PasMinimoMay {
            get {
                return ResourceManager.GetString("PasMinimoMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimo una minuscula..
        /// </summary>
        public static string PasMinimoMin {
            get {
                return ResourceManager.GetString("PasMinimoMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimo un numero..
        /// </summary>
        public static string PasMinimoNum {
            get {
                return ResourceManager.GetString("PasMinimoNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden..
        /// </summary>
        public static string PasNoIgual {
            get {
                return ResourceManager.GetString("PasNoIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La respuesta a la pregunta de seguridad es incorrecta..
        /// </summary>
        public static string PasPregInvalida {
            get {
                return ResourceManager.GetString("PasPregInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede utilizar su contraseña actual como nueva contraseña..
        /// </summary>
        public static string PasRepetida {
            get {
                return ResourceManager.GetString("PasRepetida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este perfil no puede ser eliminado porque está asignado a uno o más usuarios..
        /// </summary>
        public static string PerfEnUso {
            get {
                return ResourceManager.GetString("PerfEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un nombre de perfil válido y al menos un permiso..
        /// </summary>
        public static string PerfValido {
            get {
                return ResourceManager.GetString("PerfValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizado.
        /// </summary>
        public static string Personalizado {
            get {
                return ResourceManager.GetString("Personalizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres continuar?.
        /// </summary>
        public static string QuiereContinuar {
            get {
                return ResourceManager.GetString("QuiereContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido cargar el registro. Revise los datos y vuelva a intentarlo..
        /// </summary>
        public static string RegNoCargado {
            get {
                return ResourceManager.GetString("RegNoCargado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ningún registro coincide..
        /// </summary>
        public static string RegNoCoincide {
            get {
                return ResourceManager.GetString("RegNoCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro no pudo ser eliminado..
        /// </summary>
        public static string RegNoEliminado {
            get {
                return ResourceManager.GetString("RegNoEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un registro..
        /// </summary>
        public static string RegNoSelec {
            get {
                return ResourceManager.GetString("RegNoSelec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un registro activo..
        /// </summary>
        public static string RegSelecNoActivo {
            get {
                return ResourceManager.GetString("RegSelecNoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESTA TERMINAL SE ENCUENTRA INHABILITADA POR MANIPULACION EXTERNA DE LA BASE DE DATOS. COMUNIQUESE CON EL SOPORTE TECNICO PARA REACTICAR LA TERMINAL..
        /// </summary>
        public static string TerminalBloqueada {
            get {
                return ResourceManager.GetString("TerminalBloqueada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas.
        /// </summary>
        public static string Todas {
            get {
                return ResourceManager.GetString("Todas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario bloqueado..
        /// </summary>
        public static string UsrBloqueado {
            get {
                return ResourceManager.GetString("UsrBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su contraseña va a caducar pronto, se recomienda cambiarla..
        /// </summary>
        public static string UsrCambiaCadaPorVencer {
            get {
                return ResourceManager.GetString("UsrCambiaCadaPorVencer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su contraseña ha caducado, debe cambiarla para poder seguir utilizando el sistema..
        /// </summary>
        public static string UsrCambiaCadaVencido {
            get {
                return ResourceManager.GetString("UsrCambiaCadaVencido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se encuentra dado de baja..
        /// </summary>
        public static string UsrDadoDeBaja {
            get {
                return ResourceManager.GetString("UsrDadoDeBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario no puede contener espacios..
        /// </summary>
        public static string UsrEspacios {
            get {
                return ResourceManager.GetString("UsrEspacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario invalido. Por favor verifique que el usuario sea correcto..
        /// </summary>
        public static string UsrInvalido {
            get {
                return ResourceManager.GetString("UsrInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos..
        /// </summary>
        public static string UsrPswIncorrecto {
            get {
                return ResourceManager.GetString("UsrPswIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario reactivado..
        /// </summary>
        public static string UsrReactivado {
            get {
                return ResourceManager.GetString("UsrReactivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este empleado ya tiene un usuario asignado..
        /// </summary>
        public static string UsrYaAsignado {
            get {
                return ResourceManager.GetString("UsrYaAsignado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ese nombre de usuario ya está en uso..
        /// </summary>
        public static string UsrYaEnUso {
            get {
                return ResourceManager.GetString("UsrYaEnUso", resourceCulture);
            }
        }
    }
}
