//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista.Lenguajes {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Columnas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Columnas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vista.Lenguajes.Columnas", typeof(Columnas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir.
        /// </summary>
        internal static string abrir {
            get {
                return ResourceManager.GetString("abrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accion.
        /// </summary>
        internal static string accion {
            get {
                return ResourceManager.GetString("accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año.
        /// </summary>
        internal static string año {
            get {
                return ResourceManager.GetString("año", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string apellido {
            get {
                return ResourceManager.GetString("apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        internal static string apellidos {
            get {
                return ResourceManager.GetString("apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área.
        /// </summary>
        internal static string area {
            get {
                return ResourceManager.GetString("area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área.
        /// </summary>
        internal static string área {
            get {
                return ResourceManager.GetString("área", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capacitación.
        /// </summary>
        internal static string capacitacion {
            get {
                return ResourceManager.GetString("capacitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría.
        /// </summary>
        internal static string categoria {
            get {
                return ResourceManager.GetString("categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convenio.
        /// </summary>
        internal static string convenio {
            get {
                return ResourceManager.GetString("convenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CUIT/CUIL.
        /// </summary>
        internal static string cuil {
            get {
                return ResourceManager.GetString("cuil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CUIT/CUIL.
        /// </summary>
        internal static string cuit_cuil {
            get {
                return ResourceManager.GetString("cuit/cuil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string descripción {
            get {
                return ResourceManager.GetString("descripción", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desempeño En Equipo.
        /// </summary>
        internal static string desempeño_en_equipo {
            get {
                return ResourceManager.GetString("desempeño en equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desempeño En Equipo *.
        /// </summary>
        internal static string desempeño_en_equipo__ {
            get {
                return ResourceManager.GetString("desempeño en equipo *", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disciplina.
        /// </summary>
        internal static string disciplina {
            get {
                return ResourceManager.GetString("disciplina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disciplina *.
        /// </summary>
        internal static string disciplina__ {
            get {
                return ResourceManager.GetString("disciplina *", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        internal static string dni {
            get {
                return ResourceManager.GetString("dni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efectividad En Las Tareas.
        /// </summary>
        internal static string efectividad_en_las_tareas {
            get {
                return ResourceManager.GetString("efectividad en las tareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efectividad En Las Tareas *.
        /// </summary>
        internal static string efectividad_en_las_tareas__ {
            get {
                return ResourceManager.GetString("efectividad en las tareas *", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Egreso.
        /// </summary>
        internal static string egreso {
            get {
                return ResourceManager.GetString("egreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string eliminar {
            get {
                return ResourceManager.GetString("eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        internal static string empresa {
            get {
                return ResourceManager.GetString("empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrevista.
        /// </summary>
        internal static string entrevista {
            get {
                return ResourceManager.GetString("entrevista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrevistador.
        /// </summary>
        internal static string entrevistador {
            get {
                return ResourceManager.GetString("entrevistador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Etapa.
        /// </summary>
        internal static string etapa {
            get {
                return ResourceManager.GetString("etapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Externo/Interno.
        /// </summary>
        internal static string externo_interno {
            get {
                return ResourceManager.GetString("externo/interno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Externo/Interno2.
        /// </summary>
        internal static string externo_interno2 {
            get {
                return ResourceManager.GetString("externo/interno2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string fecha {
            get {
                return ResourceManager.GetString("fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Alta.
        /// </summary>
        internal static string fecha_alta {
            get {
                return ResourceManager.GetString("fecha alta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Egreso.
        /// </summary>
        internal static string fecha_egreso {
            get {
                return ResourceManager.GetString("fecha_egreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Entrega.
        /// </summary>
        internal static string fecha_entrega {
            get {
                return ResourceManager.GetString("fecha entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Ingreso.
        /// </summary>
        internal static string fecha_ingreso {
            get {
                return ResourceManager.GetString("fecha_ingreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Recepción.
        /// </summary>
        internal static string fecha_recepción {
            get {
                return ResourceManager.GetString("fecha recepción", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Solicitud.
        /// </summary>
        internal static string fecha_solicitud {
            get {
                return ResourceManager.GetString("fecha solicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        internal static string grupo {
            get {
                return ResourceManager.GetString("grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horas Laborales.
        /// </summary>
        internal static string horas_laborales {
            get {
                return ResourceManager.GetString("horas_laborales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Usuario.
        /// </summary>
        internal static string id_usuario {
            get {
                return ResourceManager.GetString("id usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string idiomanombre {
            get {
                return ResourceManager.GetString("idiomanombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingreso.
        /// </summary>
        internal static string ingreso {
            get {
                return ResourceManager.GetString("ingreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Institución.
        /// </summary>
        internal static string institucion {
            get {
                return ResourceManager.GetString("institucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jornada.
        /// </summary>
        internal static string jornada {
            get {
                return ResourceManager.GetString("jornada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justificada.
        /// </summary>
        internal static string justificada {
            get {
                return ResourceManager.GetString("justificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lugar.
        /// </summary>
        internal static string lugar {
            get {
                return ResourceManager.GetString("lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje.
        /// </summary>
        internal static string mensaje {
            get {
                return ResourceManager.GetString("mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes De Evaluación.
        /// </summary>
        internal static string mes_de_evaluacion {
            get {
                return ResourceManager.GetString("mes de evaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        internal static string modificar {
            get {
                return ResourceManager.GetString("modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Motivo.
        /// </summary>
        internal static string motivo {
            get {
                return ResourceManager.GetString("motivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        internal static string nivel {
            get {
                return ResourceManager.GetString("nivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel2.
        /// </summary>
        internal static string nivel2 {
            get {
                return ResourceManager.GetString("nivel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Categoría.
        /// </summary>
        internal static string nombre_categoria {
            get {
                return ResourceManager.GetString("nombre_categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Y Apellido.
        /// </summary>
        internal static string nombre_y_apellido {
            get {
                return ResourceManager.GetString("nombre y apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Y Apellido.
        /// </summary>
        internal static string nombreapellido {
            get {
                return ResourceManager.GetString("nombreapellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        internal static string nombres {
            get {
                return ResourceManager.GetString("nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obligatoria.
        /// </summary>
        internal static string obligatoria {
            get {
                return ResourceManager.GetString("obligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        internal static string observaciones {
            get {
                return ResourceManager.GetString("observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro Motivo.
        /// </summary>
        internal static string otro_motivo {
            get {
                return ResourceManager.GetString("otro_motivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        internal static string perfil {
            get {
                return ResourceManager.GetString("perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodo.
        /// </summary>
        internal static string periodo {
            get {
                return ResourceManager.GetString("periodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal A Cargo.
        /// </summary>
        internal static string personal_a_cargo {
            get {
                return ResourceManager.GetString("personal_a_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Progreso.
        /// </summary>
        internal static string progreso {
            get {
                return ResourceManager.GetString("progreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puesto.
        /// </summary>
        internal static string puesto {
            get {
                return ResourceManager.GetString("puesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puesto A Postularse.
        /// </summary>
        internal static string puesto_a_postularse {
            get {
                return ResourceManager.GetString("puesto a postularse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntualidad.
        /// </summary>
        internal static string puntualidad {
            get {
                return ResourceManager.GetString("puntualidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntualidad *.
        /// </summary>
        internal static string puntualidad__ {
            get {
                return ResourceManager.GetString("puntualidad *", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación Con Superiores.
        /// </summary>
        internal static string relacion_con_superiores {
            get {
                return ResourceManager.GetString("relacion con superiores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación Con Superiores *.
        /// </summary>
        internal static string relación_con_superiores__ {
            get {
                return ResourceManager.GetString("relación con superiores *", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad Salud.
        /// </summary>
        internal static string seguridad_salud {
            get {
                return ResourceManager.GetString("seguridad_salud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad Y Salud.
        /// </summary>
        internal static string seguridad_y_salud {
            get {
                return ResourceManager.GetString("seguridad y salud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sueldo.
        /// </summary>
        internal static string sueldo {
            get {
                return ResourceManager.GetString("sueldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sueldos.
        /// </summary>
        internal static string sueldos {
            get {
                return ResourceManager.GetString("sueldos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo Estimado.
        /// </summary>
        internal static string tiempo_estimado {
            get {
                return ResourceManager.GetString("tiempo_estimado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string tipo {
            get {
                return ResourceManager.GetString("tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título.
        /// </summary>
        internal static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
    }
}
